# API Keys Configuration
# Copy this file to config.yaml and fill in your API keys
api_keys:
  openai: "your_openai_api_key_here"
  anthropic: "your_anthropic_api_key_here"
  deepseek: "your_deepseek_api_key_here"

# Model Configuration
default_model: "gpt-4o"